#!/usr/bin/env python3
"""
Step 2: recover backlinked targets that are not in legacy/crawl from the
Wayback Machine.

    python3 legacy/scripts/wayback.py

For every targets.csv row with action recover-page-from-wayback,
recover-pdf-from-wayback or recover-image-from-wayback:

  1. ask archive.org's availability API for the snapshot closest to the
     program's last year (2014) for each URL variant (www / bare host, the raw
     Ahrefs target spellings, and the corrected path for typo variants);
  2. accept only a 200 snapshot taken before the site went dark (2015-07);
  3. download the raw capture (`<timestamp>id_/` — no Wayback toolbar) to
       pages  -> legacy/wayback/pages/<encoded-path>.html  (extract.py reads these)
       files  -> public/<original path>                    (served at the old URL)
     and check the bytes are really a PDF/image/HTML page, not an error page.

Every attempt and its result goes to legacy/wayback-recovery.md. A file that
already exists at its destination is kept and reported as recovered, so the
script can be re-run after fetching captures some other way.
"""

from __future__ import annotations

import csv
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from extract import file_stem  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
LEGACY = ROOT / 'legacy'
PAGES = LEGACY / 'wayback' / 'pages'
PUBLIC = ROOT / 'public'
REPORT = LEGACY / 'wayback-recovery.md'

ACTIONS = {'recover-page-from-wayback', 'recover-pdf-from-wayback', 'recover-image-from-wayback'}
CUTOFF = '20150701'

# Targets deliberately not restored even if a capture exists; they 301 instead
# (see redirects.py). Checked before any network request.
NOT_RESTORED = {
    '/product/original-non-hydrogenated-margarine-7-g-foodservice-item':
        'capture 20120512170259 exists, but it is a one-product Becel/Unilever listing whose only '
        'content is the licensed-symbol criteria (~30 words); not restored, redirects to /page/products-overview',
    '/images/index_logo.jpg':
        'the old Health Check logo; logos are not re-published (README decision 4), redirects to /',
}

# Typo / variant targets and the path they meant.
CORRECTED = {
    '/story/health-check-exitl': '/story/health-check-exit',
    '/page/nutrients-women>': '/page/nutrients-women',
}


def get(url: str, tries: int = 4) -> bytes:
    last: Exception | None = None
    for i in range(tries):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'healthcheck.org legacy recovery'})
            with urllib.request.urlopen(req, timeout=60) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code in (403, 404, 451):
                raise
            last = e
        except Exception as e:  # network resets, timeouts
            last = e
        time.sleep(2 ** (i + 1))
    raise last  # type: ignore[misc]


def variants(row: dict, raw_targets: list[str]) -> list[str]:
    paths = [row['path']]
    if row['path'] in CORRECTED:
        paths.append(CORRECTED[row['path']])
    out: list[str] = []
    for p in paths:
        enc = urllib.parse.quote(p, safe="/?&=")
        for host in ('www.healthcheck.org', 'healthcheck.org'):
            out += [f'http://{host}{enc}', f'{host}{enc}']
    out += raw_targets
    seen, uniq = set(), []
    for u in out:
        if u not in seen:
            seen.add(u)
            uniq.append(u)
    return uniq


def closest(url: str) -> dict | None:
    api = 'https://archive.org/wayback/available?' + urllib.parse.urlencode({'url': url, 'timestamp': '20140601'})
    data = json.loads(get(api))
    snap = (data.get('archived_snapshots') or {}).get('closest')
    if snap and snap.get('status') == '200' and snap['timestamp'] < CUTOFF:
        return snap
    return snap and {**snap, 'rejected': True}


def looks_right(kind: str, body: bytes) -> bool:
    if kind == 'pdf':
        return body[:5] == b'%PDF-'
    if kind == 'image':
        return body[:3] in (b'\xff\xd8\xff', b'GIF') or body[:4] == b'\x89PNG'
    text = body[:20000].decode('utf-8', 'replace')
    return 'id="content-area"' in text or 'id="content"' in text


def main() -> int:
    rows = list(csv.DictReader(open(LEGACY / 'targets.csv', encoding='utf-8')))
    raw = {t['path']: t.get('raw_targets', []) for t in json.load(open(LEGACY / 'targets.json', encoding='utf-8'))}
    PAGES.mkdir(parents=True, exist_ok=True)

    lines = [
        '# Wayback recovery log',
        '',
        'Generated by `legacy/scripts/wayback.py`. Snapshots are accepted only with HTTP 200 and a',
        f'timestamp before {CUTOFF[:4]}-{CUTOFF[4:6]} (after that the domain served other content).',
        '',
        'In the run that produced this log, archive.org (availability API) was reachable but every',
        'connection to web.archive.org (the captures themselves) was reset by the sandbox network',
        'policy, so no file could be downloaded here. The two recipe pages were fetched through a',
        'remote fetcher and saved under legacy/wayback/pages/ (each file names its capture URL);',
        're-running this script with web.archive.org reachable retries everything else.',
        '',
    ]
    summary: list[tuple[str, str, str]] = []

    for row in rows:
        if row['action'] not in ACTIONS:
            continue
        kind = {'recover-page-from-wayback': 'page', 'recover-pdf-from-wayback': 'pdf'}.get(row['action'], 'image')
        path = row['path']
        dest = PAGES / (file_stem(path) + '.html') if kind == 'page' else PUBLIC / path.lstrip('/')
        lines += [f'## `{path}`', '', f'- kind: {kind}; destination: `{dest.relative_to(ROOT)}`']

        if path in NOT_RESTORED:
            lines += [f'- **result: not restored** ({NOT_RESTORED[path]})', '']
            summary.append((path, 'not restored', NOT_RESTORED[path]))
            print(f'not restored   {path}')
            continue

        if dest.is_file() and dest.stat().st_size and looks_right(kind, dest.read_bytes()):
            note = ''
            head = dest.read_bytes()[:600].decode('utf-8', 'replace') if kind == 'page' else ''
            if 'Wayback capture' in head:
                note = ' — ' + head.split('Wayback capture', 1)[1].split('\n', 1)[0].strip()
            lines += [f'- already present at destination — kept{note}', '']
            summary.append((path, 'recovered', 'already present' + note))
            continue

        result = 'not recovered'
        detail = 'no 200 snapshot before the cutoff'
        for v in variants(row, raw.get(path, [])):
            try:
                snap = closest(v)
            except Exception as e:
                lines.append(f'- availability `{v}`: error {e}')
                continue
            if not snap:
                lines.append(f'- availability `{v}`: no snapshot')
                continue
            if snap.get('rejected'):
                lines.append(f'- availability `{v}`: {snap["timestamp"]} status {snap.get("status")} — rejected')
                continue
            ts, orig = snap['timestamp'], snap['url'].split('/', 5)[5]
            raw_url = f'https://web.archive.org/web/{ts}id_/{orig}'
            lines.append(f'- availability `{v}`: {ts} → `{raw_url}`')
            try:
                body = get(raw_url, tries=2)
            except Exception as e:
                lines.append(f'  - download failed: {type(e).__name__}: {e}')
                detail = f'snapshot {ts} exists but download failed ({type(e).__name__})'
                continue
            if not looks_right(kind, body):
                lines.append(f'  - downloaded {len(body)} bytes but it is not a {kind} — rejected')
                detail = f'snapshot {ts} is not a usable {kind}'
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(body)
            lines.append(f'  - saved {len(body)} bytes')
            result, detail = 'recovered', f'snapshot {ts}'
            break
        lines += [f'- **result: {result}** ({detail})', '']
        summary.append((path, result, detail))
        print(f'{result:14s} {path}  — {detail}')

    lines += ['## Summary', '', '| path | result | detail |', '| --- | --- | --- |']
    lines += [f'| `{p}` | {r} | {d} |' for p, r, d in summary]
    REPORT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
