import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Pages restored from the old healthcheck.org (see legacy/README.md),
 * generated by legacy/scripts/extract.py. Routing uses `path`, never the
 * filename: it is the page's original URL, byte for byte.
 */
const legacy = defineCollection({
  loader: glob({ pattern: '*.md', base: './src/content/legacy' }),
  schema: z.object({
    path: z.string().startsWith('/'),
    title: z.string(),
    /** The page's own heading (the old <h1> was the site name on every page). */
    heading: z.string(),
    description: z.string(),
    originalTitle: z.string(),
    section: z.enum(['page', 'story', 'content', 'blog', 'faq', 'recipe', 'other']),
    crawlFile: z.string().nullable(),
    referringDomains: z.number().int(),
    maxDR: z.number().int(),
    archived: z.literal(true),
    /** Press-release date as printed on the old page (MM-DD-YYYY). */
    date: z.string().optional(),
    /** Blog "Posted by … on …" line. */
    byline: z.string().optional(),
    /** Set when the page came from the Wayback Machine rather than the crawl. */
    source: z.literal('wayback').optional(),
    wordCount: z.number().int(),
  }),
});

export const collections = { legacy };
